#if TARGET_OS_SIMULATOR
#if 0
#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="PayUCheckoutProBaseKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit15BaseAPIResponse")
@interface BaseAPIResponse : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PayUPaymentParam;
@protocol OnePayUBaseLayerDelegate;
@protocol OnePayUBaseIndividualPaymentDelegate;
@class FetchPaymentOptionResponse;
@class PaymentOption;
enum ScreenState : NSInteger;
@class UIViewController;
@class ImageParam;
@class UIImage;
@class CheckEligibilityResponse;
@class PaymentMode;

SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit9BaseLayer")
@interface BaseLayer : NSObject
@property (nonatomic, strong) PayUPaymentParam * _Nonnull basePaymentParam;
@property (nonatomic, weak) id <OnePayUBaseLayerDelegate> _Nullable delegate;
@property (nonatomic, weak) id <OnePayUBaseIndividualPaymentDelegate> _Nullable individualPaymentDelegate;
- (nonnull instancetype)initWithPaymentParam:(PayUPaymentParam * _Nonnull)paymentParam OBJC_DESIGNATED_INITIALIZER;
- (void)fetchPaymentOptionsOnCompletion:(void (^ _Nonnull)(FetchPaymentOptionResponse * _Nonnull))onCompletion;
- (void)makePaymentWithPaymentOption:(PaymentOption * _Nonnull)paymentOption screenState:(enum ScreenState)screenState onViewController:(UIViewController * _Nonnull)onViewController onError:(void (^ _Nonnull)(NSError * _Nullable))onError;
- (BOOL)cancelCurrentPayment SWIFT_WARN_UNUSED_RESULT;
- (void)imageOf:(ImageParam * _Nonnull)imageParam onCompletion:(void (^ _Nonnull)(UIImage * _Nullable))onCompletion;
- (void)checkEligibilityWithPaymentOption:(PaymentOption * _Nonnull)paymentOption onCompletion:(void (^ _Nonnull)(CheckEligibilityResponse * _Nonnull))onCompletion;
- (void)emiDetailsOnCompletion:(void (^ _Nonnull)(PaymentMode * _Nullable, NSError * _Nullable))onCompletion;
- (void)deleteSavedOptionWithPaymentOption:(PaymentOption * _Nonnull)paymentOption onCompletion:(void (^ _Nonnull)(CheckEligibilityResponse * _Nonnull))onCompletion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum PaymentType : NSInteger;

SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit13PaymentOption")
@interface PaymentOption : NSObject
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable unavailableReason;
@property (nonatomic, copy) NSString * _Nullable offerDetail;
@property (nonatomic, copy) NSString * _Nullable paymentOptionID;
@property (nonatomic) id _Nullable customObj;
@property (nonatomic, readonly) enum PaymentType paymentType;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit4CCDC")
@interface CCDC : PaymentOption
@property (nonatomic, copy) NSString * _Nullable cardNumber;
@property (nonatomic, copy) NSString * _Nullable cvv;
@property (nonatomic, copy) NSString * _Nullable nameOnCard;
@property (nonatomic, copy) NSString * _Nullable cardAlias;
@property (nonatomic) BOOL shouldSaveCard;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, CardScheme, open) {
  CardSchemeMasterCard = 0,
  CardSchemeVisa = 1,
  CardSchemeJcb = 2,
  CardSchemeAmex = 3,
  CardSchemeMaestro = 4,
  CardSchemeRupay = 5,
  CardSchemeDiscover = 6,
  CardSchemeDinersClub = 7,
  CardSchemeLaser = 8,
  CardSchemeStateBankMaestro = 9,
  CardSchemeUnknown = 10,
};

typedef SWIFT_ENUM(NSInteger, CardType, open) {
  CardTypeCc = 0,
  CardTypeDc = 1,
};


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit24CheckEligibilityResponse")
@interface CheckEligibilityResponse : BaseAPIResponse
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit3EMI")
@interface EMI : CCDC
@property (nonatomic, copy) NSString * _Nonnull bankShortName;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable supportedBins;
@property (nonatomic) double minimumTxnAmount;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, Environment, open) {
  EnvironmentProduction = 0,
  EnvironmentTest = 1,
};


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit26FetchPaymentOptionResponse")
@interface FetchPaymentOptionResponse : BaseAPIResponse
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit10ImageParam")
@interface ImageParam : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit10NetBanking")
@interface NetBanking : PaymentOption
@property (nonatomic, copy) NSString * _Nullable maskedAccountNumber;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit8NextStep")
@interface NextStep : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP22PayUCheckoutProBaseKit36OnePayUBaseIndividualPaymentDelegate_")
@protocol OnePayUBaseIndividualPaymentDelegate
- (void)upiCollectTransactionRemainingTime:(NSInteger)remainingTime;
@end


SWIFT_PROTOCOL("_TtP22PayUCheckoutProBaseKit24OnePayUBaseLayerDelegate_")
@protocol OnePayUBaseLayerDelegate
- (void)paymentSuccessWithResponse:(id _Nullable)response;
- (void)paymentFailureWithResponse:(id _Nullable)response;
- (void)paymentCancelledWithResponse:(id _Nullable)response fromPaymentScreen:(BOOL)fromPaymentScreen;
- (void)error:(NSError * _Nullable)error;
- (void)getHashFor:(NSDictionary<NSString *, NSString *> * _Nonnull)param onCompletion:(void (^ _Nonnull)(NSDictionary<NSString *, NSString *> * _Nonnull))onCompletion;
- (void)nextStep:(NextStep * _Nullable)nextStep;
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit16PayUPaymentParam")
@interface PayUPaymentParam : NSObject
@property (nonatomic, copy) NSString * _Nonnull key;
@property (nonatomic, copy) NSString * _Nonnull transactionId;
@property (nonatomic, copy) NSString * _Nonnull amount;
@property (nonatomic, copy) NSString * _Nonnull productInfo;
@property (nonatomic, copy) NSString * _Nonnull firstName;
@property (nonatomic, copy) NSString * _Nonnull email;
@property (nonatomic, copy) NSString * _Nonnull phone;
@property (nonatomic, copy) NSString * _Nonnull surl;
@property (nonatomic, copy) NSString * _Nonnull furl;
@property (nonatomic, copy) NSString * _Nullable userCredential;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull additionalParam;
@property (nonatomic) enum Environment environment;
- (nonnull instancetype)initWithKey:(NSString * _Nonnull)key transactionId:(NSString * _Nonnull)transactionId amount:(NSString * _Nonnull)amount productInfo:(NSString * _Nonnull)productInfo firstName:(NSString * _Nonnull)firstName email:(NSString * _Nonnull)email phone:(NSString * _Nonnull)phone surl:(NSString * _Nonnull)surl furl:(NSString * _Nonnull)furl environment:(enum Environment)environment OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit11PaymentMode")
@interface PaymentMode : NSObject <NSCopying>
@property (nonatomic, copy) NSString * _Nullable modeName;
@property (nonatomic, copy) NSString * _Nullable subHeading;
@property (nonatomic, copy) NSString * _Nullable offerDetail;
@property (nonatomic) enum PaymentType paymentType;
@property (nonatomic, copy) NSArray<PaymentOption *> * _Nullable options;
@property (nonatomic) BOOL isDirectPaymentMode;
- (nonnull instancetype)initWithModeName:(NSString * _Nullable)modeName subHeading:(NSString * _Nullable)subHeading offerDetail:(NSString * _Nullable)offerDetail paymentType:(enum PaymentType)paymentType options:(NSArray<PaymentOption *> * _Nullable)options OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithPaymentType:(enum PaymentType)paymentType paymentOptionID:(NSString * _Nullable)paymentOptionID;
+ (PaymentMode * _Nullable)getPaymentModeFromPaymentModes:(NSArray<PaymentMode *> * _Nullable)paymentModes paymentType:(enum PaymentType)paymentType SWIFT_WARN_UNUSED_RESULT;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


typedef SWIFT_ENUM(NSInteger, PaymentType, open) {
  PaymentTypeCcdc = 0,
  PaymentTypeSavedCard = 1,
  PaymentTypeNetBanking = 2,
  PaymentTypeUpi = 3,
  PaymentTypeWallet = 4,
  PaymentTypeEmi = 5,
  PaymentTypeOther = 6,
};


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit9SavedCard")
@interface SavedCard : CCDC
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ScreenState, open) {
  ScreenStateNone = 0,
  ScreenStatePhoneNumberScreen = 1,
  ScreenStateVpaEntry = 2,
  ScreenStateUpiIntentProcessing = 3,
  ScreenStateUpiCollectProcessing = 4,
};


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit3UPI")
@interface UPI : PaymentOption
@property (nonatomic, copy) NSString * _Nullable vpa;
@property (nonatomic, copy) NSString * _Nullable scheme;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit6Wallet")
@interface Wallet : PaymentOption
@property (nonatomic, copy) NSString * _Nullable maskedAccountNumber;
@property (nonatomic, copy) NSString * _Nullable phoneNumber;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#elif defined(__i386__) && __i386__
// Generated by Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="PayUCheckoutProBaseKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit15BaseAPIResponse")
@interface BaseAPIResponse : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PayUPaymentParam;
@protocol OnePayUBaseLayerDelegate;
@protocol OnePayUBaseIndividualPaymentDelegate;
@class FetchPaymentOptionResponse;
@class PaymentOption;
enum ScreenState : NSInteger;
@class UIViewController;
@class ImageParam;
@class UIImage;
@class CheckEligibilityResponse;
@class PaymentMode;

SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit9BaseLayer")
@interface BaseLayer : NSObject
@property (nonatomic, strong) PayUPaymentParam * _Nonnull basePaymentParam;
@property (nonatomic, weak) id <OnePayUBaseLayerDelegate> _Nullable delegate;
@property (nonatomic, weak) id <OnePayUBaseIndividualPaymentDelegate> _Nullable individualPaymentDelegate;
- (nonnull instancetype)initWithPaymentParam:(PayUPaymentParam * _Nonnull)paymentParam OBJC_DESIGNATED_INITIALIZER;
- (void)fetchPaymentOptionsOnCompletion:(void (^ _Nonnull)(FetchPaymentOptionResponse * _Nonnull))onCompletion;
- (void)makePaymentWithPaymentOption:(PaymentOption * _Nonnull)paymentOption screenState:(enum ScreenState)screenState onViewController:(UIViewController * _Nonnull)onViewController onError:(void (^ _Nonnull)(NSError * _Nullable))onError;
- (BOOL)cancelCurrentPayment SWIFT_WARN_UNUSED_RESULT;
- (void)imageOf:(ImageParam * _Nonnull)imageParam onCompletion:(void (^ _Nonnull)(UIImage * _Nullable))onCompletion;
- (void)checkEligibilityWithPaymentOption:(PaymentOption * _Nonnull)paymentOption onCompletion:(void (^ _Nonnull)(CheckEligibilityResponse * _Nonnull))onCompletion;
- (void)emiDetailsOnCompletion:(void (^ _Nonnull)(PaymentMode * _Nullable, NSError * _Nullable))onCompletion;
- (void)deleteSavedOptionWithPaymentOption:(PaymentOption * _Nonnull)paymentOption onCompletion:(void (^ _Nonnull)(CheckEligibilityResponse * _Nonnull))onCompletion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum PaymentType : NSInteger;

SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit13PaymentOption")
@interface PaymentOption : NSObject
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable unavailableReason;
@property (nonatomic, copy) NSString * _Nullable offerDetail;
@property (nonatomic, copy) NSString * _Nullable paymentOptionID;
@property (nonatomic) id _Nullable customObj;
@property (nonatomic, readonly) enum PaymentType paymentType;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit4CCDC")
@interface CCDC : PaymentOption
@property (nonatomic, copy) NSString * _Nullable cardNumber;
@property (nonatomic, copy) NSString * _Nullable cvv;
@property (nonatomic, copy) NSString * _Nullable nameOnCard;
@property (nonatomic, copy) NSString * _Nullable cardAlias;
@property (nonatomic) BOOL shouldSaveCard;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, CardScheme, open) {
  CardSchemeMasterCard = 0,
  CardSchemeVisa = 1,
  CardSchemeJcb = 2,
  CardSchemeAmex = 3,
  CardSchemeMaestro = 4,
  CardSchemeRupay = 5,
  CardSchemeDiscover = 6,
  CardSchemeDinersClub = 7,
  CardSchemeLaser = 8,
  CardSchemeStateBankMaestro = 9,
  CardSchemeUnknown = 10,
};

typedef SWIFT_ENUM(NSInteger, CardType, open) {
  CardTypeCc = 0,
  CardTypeDc = 1,
};


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit24CheckEligibilityResponse")
@interface CheckEligibilityResponse : BaseAPIResponse
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit3EMI")
@interface EMI : CCDC
@property (nonatomic, copy) NSString * _Nonnull bankShortName;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable supportedBins;
@property (nonatomic) double minimumTxnAmount;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, Environment, open) {
  EnvironmentProduction = 0,
  EnvironmentTest = 1,
};


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit26FetchPaymentOptionResponse")
@interface FetchPaymentOptionResponse : BaseAPIResponse
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit10ImageParam")
@interface ImageParam : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit10NetBanking")
@interface NetBanking : PaymentOption
@property (nonatomic, copy) NSString * _Nullable maskedAccountNumber;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit8NextStep")
@interface NextStep : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP22PayUCheckoutProBaseKit36OnePayUBaseIndividualPaymentDelegate_")
@protocol OnePayUBaseIndividualPaymentDelegate
- (void)upiCollectTransactionRemainingTime:(NSInteger)remainingTime;
@end


SWIFT_PROTOCOL("_TtP22PayUCheckoutProBaseKit24OnePayUBaseLayerDelegate_")
@protocol OnePayUBaseLayerDelegate
- (void)paymentSuccessWithResponse:(id _Nullable)response;
- (void)paymentFailureWithResponse:(id _Nullable)response;
- (void)paymentCancelledWithResponse:(id _Nullable)response fromPaymentScreen:(BOOL)fromPaymentScreen;
- (void)error:(NSError * _Nullable)error;
- (void)getHashFor:(NSDictionary<NSString *, NSString *> * _Nonnull)param onCompletion:(void (^ _Nonnull)(NSDictionary<NSString *, NSString *> * _Nonnull))onCompletion;
- (void)nextStep:(NextStep * _Nullable)nextStep;
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit16PayUPaymentParam")
@interface PayUPaymentParam : NSObject
@property (nonatomic, copy) NSString * _Nonnull key;
@property (nonatomic, copy) NSString * _Nonnull transactionId;
@property (nonatomic, copy) NSString * _Nonnull amount;
@property (nonatomic, copy) NSString * _Nonnull productInfo;
@property (nonatomic, copy) NSString * _Nonnull firstName;
@property (nonatomic, copy) NSString * _Nonnull email;
@property (nonatomic, copy) NSString * _Nonnull phone;
@property (nonatomic, copy) NSString * _Nonnull surl;
@property (nonatomic, copy) NSString * _Nonnull furl;
@property (nonatomic, copy) NSString * _Nullable userCredential;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull additionalParam;
@property (nonatomic) enum Environment environment;
- (nonnull instancetype)initWithKey:(NSString * _Nonnull)key transactionId:(NSString * _Nonnull)transactionId amount:(NSString * _Nonnull)amount productInfo:(NSString * _Nonnull)productInfo firstName:(NSString * _Nonnull)firstName email:(NSString * _Nonnull)email phone:(NSString * _Nonnull)phone surl:(NSString * _Nonnull)surl furl:(NSString * _Nonnull)furl environment:(enum Environment)environment OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit11PaymentMode")
@interface PaymentMode : NSObject <NSCopying>
@property (nonatomic, copy) NSString * _Nullable modeName;
@property (nonatomic, copy) NSString * _Nullable subHeading;
@property (nonatomic, copy) NSString * _Nullable offerDetail;
@property (nonatomic) enum PaymentType paymentType;
@property (nonatomic, copy) NSArray<PaymentOption *> * _Nullable options;
@property (nonatomic) BOOL isDirectPaymentMode;
- (nonnull instancetype)initWithModeName:(NSString * _Nullable)modeName subHeading:(NSString * _Nullable)subHeading offerDetail:(NSString * _Nullable)offerDetail paymentType:(enum PaymentType)paymentType options:(NSArray<PaymentOption *> * _Nullable)options OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithPaymentType:(enum PaymentType)paymentType paymentOptionID:(NSString * _Nullable)paymentOptionID;
+ (PaymentMode * _Nullable)getPaymentModeFromPaymentModes:(NSArray<PaymentMode *> * _Nullable)paymentModes paymentType:(enum PaymentType)paymentType SWIFT_WARN_UNUSED_RESULT;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


typedef SWIFT_ENUM(NSInteger, PaymentType, open) {
  PaymentTypeCcdc = 0,
  PaymentTypeSavedCard = 1,
  PaymentTypeNetBanking = 2,
  PaymentTypeUpi = 3,
  PaymentTypeWallet = 4,
  PaymentTypeEmi = 5,
  PaymentTypeOther = 6,
};


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit9SavedCard")
@interface SavedCard : CCDC
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ScreenState, open) {
  ScreenStateNone = 0,
  ScreenStatePhoneNumberScreen = 1,
  ScreenStateVpaEntry = 2,
  ScreenStateUpiIntentProcessing = 3,
  ScreenStateUpiCollectProcessing = 4,
};


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit3UPI")
@interface UPI : PaymentOption
@property (nonatomic, copy) NSString * _Nullable vpa;
@property (nonatomic, copy) NSString * _Nullable scheme;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit6Wallet")
@interface Wallet : PaymentOption
@property (nonatomic, copy) NSString * _Nullable maskedAccountNumber;
@property (nonatomic, copy) NSString * _Nullable phoneNumber;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#endif
#else
#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="PayUCheckoutProBaseKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit15BaseAPIResponse")
@interface BaseAPIResponse : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PayUPaymentParam;
@protocol OnePayUBaseLayerDelegate;
@protocol OnePayUBaseIndividualPaymentDelegate;
@class FetchPaymentOptionResponse;
@class PaymentOption;
enum ScreenState : NSInteger;
@class UIViewController;
@class ImageParam;
@class UIImage;
@class CheckEligibilityResponse;
@class PaymentMode;

SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit9BaseLayer")
@interface BaseLayer : NSObject
@property (nonatomic, strong) PayUPaymentParam * _Nonnull basePaymentParam;
@property (nonatomic, weak) id <OnePayUBaseLayerDelegate> _Nullable delegate;
@property (nonatomic, weak) id <OnePayUBaseIndividualPaymentDelegate> _Nullable individualPaymentDelegate;
- (nonnull instancetype)initWithPaymentParam:(PayUPaymentParam * _Nonnull)paymentParam OBJC_DESIGNATED_INITIALIZER;
- (void)fetchPaymentOptionsOnCompletion:(void (^ _Nonnull)(FetchPaymentOptionResponse * _Nonnull))onCompletion;
- (void)makePaymentWithPaymentOption:(PaymentOption * _Nonnull)paymentOption screenState:(enum ScreenState)screenState onViewController:(UIViewController * _Nonnull)onViewController onError:(void (^ _Nonnull)(NSError * _Nullable))onError;
- (BOOL)cancelCurrentPayment SWIFT_WARN_UNUSED_RESULT;
- (void)imageOf:(ImageParam * _Nonnull)imageParam onCompletion:(void (^ _Nonnull)(UIImage * _Nullable))onCompletion;
- (void)checkEligibilityWithPaymentOption:(PaymentOption * _Nonnull)paymentOption onCompletion:(void (^ _Nonnull)(CheckEligibilityResponse * _Nonnull))onCompletion;
- (void)emiDetailsOnCompletion:(void (^ _Nonnull)(PaymentMode * _Nullable, NSError * _Nullable))onCompletion;
- (void)deleteSavedOptionWithPaymentOption:(PaymentOption * _Nonnull)paymentOption onCompletion:(void (^ _Nonnull)(CheckEligibilityResponse * _Nonnull))onCompletion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum PaymentType : NSInteger;

SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit13PaymentOption")
@interface PaymentOption : NSObject
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable unavailableReason;
@property (nonatomic, copy) NSString * _Nullable offerDetail;
@property (nonatomic, copy) NSString * _Nullable paymentOptionID;
@property (nonatomic) id _Nullable customObj;
@property (nonatomic, readonly) enum PaymentType paymentType;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit4CCDC")
@interface CCDC : PaymentOption
@property (nonatomic, copy) NSString * _Nullable cardNumber;
@property (nonatomic, copy) NSString * _Nullable cvv;
@property (nonatomic, copy) NSString * _Nullable nameOnCard;
@property (nonatomic, copy) NSString * _Nullable cardAlias;
@property (nonatomic) BOOL shouldSaveCard;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, CardScheme, open) {
  CardSchemeMasterCard = 0,
  CardSchemeVisa = 1,
  CardSchemeJcb = 2,
  CardSchemeAmex = 3,
  CardSchemeMaestro = 4,
  CardSchemeRupay = 5,
  CardSchemeDiscover = 6,
  CardSchemeDinersClub = 7,
  CardSchemeLaser = 8,
  CardSchemeStateBankMaestro = 9,
  CardSchemeUnknown = 10,
};

typedef SWIFT_ENUM(NSInteger, CardType, open) {
  CardTypeCc = 0,
  CardTypeDc = 1,
};


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit24CheckEligibilityResponse")
@interface CheckEligibilityResponse : BaseAPIResponse
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit3EMI")
@interface EMI : CCDC
@property (nonatomic, copy) NSString * _Nonnull bankShortName;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable supportedBins;
@property (nonatomic) double minimumTxnAmount;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, Environment, open) {
  EnvironmentProduction = 0,
  EnvironmentTest = 1,
};


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit26FetchPaymentOptionResponse")
@interface FetchPaymentOptionResponse : BaseAPIResponse
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit10ImageParam")
@interface ImageParam : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit10NetBanking")
@interface NetBanking : PaymentOption
@property (nonatomic, copy) NSString * _Nullable maskedAccountNumber;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit8NextStep")
@interface NextStep : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP22PayUCheckoutProBaseKit36OnePayUBaseIndividualPaymentDelegate_")
@protocol OnePayUBaseIndividualPaymentDelegate
- (void)upiCollectTransactionRemainingTime:(NSInteger)remainingTime;
@end


SWIFT_PROTOCOL("_TtP22PayUCheckoutProBaseKit24OnePayUBaseLayerDelegate_")
@protocol OnePayUBaseLayerDelegate
- (void)paymentSuccessWithResponse:(id _Nullable)response;
- (void)paymentFailureWithResponse:(id _Nullable)response;
- (void)paymentCancelledWithResponse:(id _Nullable)response fromPaymentScreen:(BOOL)fromPaymentScreen;
- (void)error:(NSError * _Nullable)error;
- (void)getHashFor:(NSDictionary<NSString *, NSString *> * _Nonnull)param onCompletion:(void (^ _Nonnull)(NSDictionary<NSString *, NSString *> * _Nonnull))onCompletion;
- (void)nextStep:(NextStep * _Nullable)nextStep;
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit16PayUPaymentParam")
@interface PayUPaymentParam : NSObject
@property (nonatomic, copy) NSString * _Nonnull key;
@property (nonatomic, copy) NSString * _Nonnull transactionId;
@property (nonatomic, copy) NSString * _Nonnull amount;
@property (nonatomic, copy) NSString * _Nonnull productInfo;
@property (nonatomic, copy) NSString * _Nonnull firstName;
@property (nonatomic, copy) NSString * _Nonnull email;
@property (nonatomic, copy) NSString * _Nonnull phone;
@property (nonatomic, copy) NSString * _Nonnull surl;
@property (nonatomic, copy) NSString * _Nonnull furl;
@property (nonatomic, copy) NSString * _Nullable userCredential;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull additionalParam;
@property (nonatomic) enum Environment environment;
- (nonnull instancetype)initWithKey:(NSString * _Nonnull)key transactionId:(NSString * _Nonnull)transactionId amount:(NSString * _Nonnull)amount productInfo:(NSString * _Nonnull)productInfo firstName:(NSString * _Nonnull)firstName email:(NSString * _Nonnull)email phone:(NSString * _Nonnull)phone surl:(NSString * _Nonnull)surl furl:(NSString * _Nonnull)furl environment:(enum Environment)environment OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit11PaymentMode")
@interface PaymentMode : NSObject <NSCopying>
@property (nonatomic, copy) NSString * _Nullable modeName;
@property (nonatomic, copy) NSString * _Nullable subHeading;
@property (nonatomic, copy) NSString * _Nullable offerDetail;
@property (nonatomic) enum PaymentType paymentType;
@property (nonatomic, copy) NSArray<PaymentOption *> * _Nullable options;
@property (nonatomic) BOOL isDirectPaymentMode;
- (nonnull instancetype)initWithModeName:(NSString * _Nullable)modeName subHeading:(NSString * _Nullable)subHeading offerDetail:(NSString * _Nullable)offerDetail paymentType:(enum PaymentType)paymentType options:(NSArray<PaymentOption *> * _Nullable)options OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithPaymentType:(enum PaymentType)paymentType paymentOptionID:(NSString * _Nullable)paymentOptionID;
+ (PaymentMode * _Nullable)getPaymentModeFromPaymentModes:(NSArray<PaymentMode *> * _Nullable)paymentModes paymentType:(enum PaymentType)paymentType SWIFT_WARN_UNUSED_RESULT;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


typedef SWIFT_ENUM(NSInteger, PaymentType, open) {
  PaymentTypeCcdc = 0,
  PaymentTypeSavedCard = 1,
  PaymentTypeNetBanking = 2,
  PaymentTypeUpi = 3,
  PaymentTypeWallet = 4,
  PaymentTypeEmi = 5,
  PaymentTypeOther = 6,
};


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit9SavedCard")
@interface SavedCard : CCDC
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ScreenState, open) {
  ScreenStateNone = 0,
  ScreenStatePhoneNumberScreen = 1,
  ScreenStateVpaEntry = 2,
  ScreenStateUpiIntentProcessing = 3,
  ScreenStateUpiCollectProcessing = 4,
};


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit3UPI")
@interface UPI : PaymentOption
@property (nonatomic, copy) NSString * _Nullable vpa;
@property (nonatomic, copy) NSString * _Nullable scheme;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit6Wallet")
@interface Wallet : PaymentOption
@property (nonatomic, copy) NSString * _Nullable maskedAccountNumber;
@property (nonatomic, copy) NSString * _Nullable phoneNumber;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#elif defined(__ARM_ARCH_7A__) && __ARM_ARCH_7A__
// Generated by Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="PayUCheckoutProBaseKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit15BaseAPIResponse")
@interface BaseAPIResponse : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PayUPaymentParam;
@protocol OnePayUBaseLayerDelegate;
@protocol OnePayUBaseIndividualPaymentDelegate;
@class FetchPaymentOptionResponse;
@class PaymentOption;
enum ScreenState : NSInteger;
@class UIViewController;
@class ImageParam;
@class UIImage;
@class CheckEligibilityResponse;
@class PaymentMode;

SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit9BaseLayer")
@interface BaseLayer : NSObject
@property (nonatomic, strong) PayUPaymentParam * _Nonnull basePaymentParam;
@property (nonatomic, weak) id <OnePayUBaseLayerDelegate> _Nullable delegate;
@property (nonatomic, weak) id <OnePayUBaseIndividualPaymentDelegate> _Nullable individualPaymentDelegate;
- (nonnull instancetype)initWithPaymentParam:(PayUPaymentParam * _Nonnull)paymentParam OBJC_DESIGNATED_INITIALIZER;
- (void)fetchPaymentOptionsOnCompletion:(void (^ _Nonnull)(FetchPaymentOptionResponse * _Nonnull))onCompletion;
- (void)makePaymentWithPaymentOption:(PaymentOption * _Nonnull)paymentOption screenState:(enum ScreenState)screenState onViewController:(UIViewController * _Nonnull)onViewController onError:(void (^ _Nonnull)(NSError * _Nullable))onError;
- (BOOL)cancelCurrentPayment SWIFT_WARN_UNUSED_RESULT;
- (void)imageOf:(ImageParam * _Nonnull)imageParam onCompletion:(void (^ _Nonnull)(UIImage * _Nullable))onCompletion;
- (void)checkEligibilityWithPaymentOption:(PaymentOption * _Nonnull)paymentOption onCompletion:(void (^ _Nonnull)(CheckEligibilityResponse * _Nonnull))onCompletion;
- (void)emiDetailsOnCompletion:(void (^ _Nonnull)(PaymentMode * _Nullable, NSError * _Nullable))onCompletion;
- (void)deleteSavedOptionWithPaymentOption:(PaymentOption * _Nonnull)paymentOption onCompletion:(void (^ _Nonnull)(CheckEligibilityResponse * _Nonnull))onCompletion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum PaymentType : NSInteger;

SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit13PaymentOption")
@interface PaymentOption : NSObject
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable unavailableReason;
@property (nonatomic, copy) NSString * _Nullable offerDetail;
@property (nonatomic, copy) NSString * _Nullable paymentOptionID;
@property (nonatomic) id _Nullable customObj;
@property (nonatomic, readonly) enum PaymentType paymentType;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit4CCDC")
@interface CCDC : PaymentOption
@property (nonatomic, copy) NSString * _Nullable cardNumber;
@property (nonatomic, copy) NSString * _Nullable cvv;
@property (nonatomic, copy) NSString * _Nullable nameOnCard;
@property (nonatomic, copy) NSString * _Nullable cardAlias;
@property (nonatomic) BOOL shouldSaveCard;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, CardScheme, open) {
  CardSchemeMasterCard = 0,
  CardSchemeVisa = 1,
  CardSchemeJcb = 2,
  CardSchemeAmex = 3,
  CardSchemeMaestro = 4,
  CardSchemeRupay = 5,
  CardSchemeDiscover = 6,
  CardSchemeDinersClub = 7,
  CardSchemeLaser = 8,
  CardSchemeStateBankMaestro = 9,
  CardSchemeUnknown = 10,
};

typedef SWIFT_ENUM(NSInteger, CardType, open) {
  CardTypeCc = 0,
  CardTypeDc = 1,
};


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit24CheckEligibilityResponse")
@interface CheckEligibilityResponse : BaseAPIResponse
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit3EMI")
@interface EMI : CCDC
@property (nonatomic, copy) NSString * _Nonnull bankShortName;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable supportedBins;
@property (nonatomic) double minimumTxnAmount;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, Environment, open) {
  EnvironmentProduction = 0,
  EnvironmentTest = 1,
};


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit26FetchPaymentOptionResponse")
@interface FetchPaymentOptionResponse : BaseAPIResponse
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit10ImageParam")
@interface ImageParam : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit10NetBanking")
@interface NetBanking : PaymentOption
@property (nonatomic, copy) NSString * _Nullable maskedAccountNumber;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit8NextStep")
@interface NextStep : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP22PayUCheckoutProBaseKit36OnePayUBaseIndividualPaymentDelegate_")
@protocol OnePayUBaseIndividualPaymentDelegate
- (void)upiCollectTransactionRemainingTime:(NSInteger)remainingTime;
@end


SWIFT_PROTOCOL("_TtP22PayUCheckoutProBaseKit24OnePayUBaseLayerDelegate_")
@protocol OnePayUBaseLayerDelegate
- (void)paymentSuccessWithResponse:(id _Nullable)response;
- (void)paymentFailureWithResponse:(id _Nullable)response;
- (void)paymentCancelledWithResponse:(id _Nullable)response fromPaymentScreen:(BOOL)fromPaymentScreen;
- (void)error:(NSError * _Nullable)error;
- (void)getHashFor:(NSDictionary<NSString *, NSString *> * _Nonnull)param onCompletion:(void (^ _Nonnull)(NSDictionary<NSString *, NSString *> * _Nonnull))onCompletion;
- (void)nextStep:(NextStep * _Nullable)nextStep;
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit16PayUPaymentParam")
@interface PayUPaymentParam : NSObject
@property (nonatomic, copy) NSString * _Nonnull key;
@property (nonatomic, copy) NSString * _Nonnull transactionId;
@property (nonatomic, copy) NSString * _Nonnull amount;
@property (nonatomic, copy) NSString * _Nonnull productInfo;
@property (nonatomic, copy) NSString * _Nonnull firstName;
@property (nonatomic, copy) NSString * _Nonnull email;
@property (nonatomic, copy) NSString * _Nonnull phone;
@property (nonatomic, copy) NSString * _Nonnull surl;
@property (nonatomic, copy) NSString * _Nonnull furl;
@property (nonatomic, copy) NSString * _Nullable userCredential;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull additionalParam;
@property (nonatomic) enum Environment environment;
- (nonnull instancetype)initWithKey:(NSString * _Nonnull)key transactionId:(NSString * _Nonnull)transactionId amount:(NSString * _Nonnull)amount productInfo:(NSString * _Nonnull)productInfo firstName:(NSString * _Nonnull)firstName email:(NSString * _Nonnull)email phone:(NSString * _Nonnull)phone surl:(NSString * _Nonnull)surl furl:(NSString * _Nonnull)furl environment:(enum Environment)environment OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit11PaymentMode")
@interface PaymentMode : NSObject <NSCopying>
@property (nonatomic, copy) NSString * _Nullable modeName;
@property (nonatomic, copy) NSString * _Nullable subHeading;
@property (nonatomic, copy) NSString * _Nullable offerDetail;
@property (nonatomic) enum PaymentType paymentType;
@property (nonatomic, copy) NSArray<PaymentOption *> * _Nullable options;
@property (nonatomic) BOOL isDirectPaymentMode;
- (nonnull instancetype)initWithModeName:(NSString * _Nullable)modeName subHeading:(NSString * _Nullable)subHeading offerDetail:(NSString * _Nullable)offerDetail paymentType:(enum PaymentType)paymentType options:(NSArray<PaymentOption *> * _Nullable)options OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithPaymentType:(enum PaymentType)paymentType paymentOptionID:(NSString * _Nullable)paymentOptionID;
+ (PaymentMode * _Nullable)getPaymentModeFromPaymentModes:(NSArray<PaymentMode *> * _Nullable)paymentModes paymentType:(enum PaymentType)paymentType SWIFT_WARN_UNUSED_RESULT;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


typedef SWIFT_ENUM(NSInteger, PaymentType, open) {
  PaymentTypeCcdc = 0,
  PaymentTypeSavedCard = 1,
  PaymentTypeNetBanking = 2,
  PaymentTypeUpi = 3,
  PaymentTypeWallet = 4,
  PaymentTypeEmi = 5,
  PaymentTypeOther = 6,
};


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit9SavedCard")
@interface SavedCard : CCDC
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ScreenState, open) {
  ScreenStateNone = 0,
  ScreenStatePhoneNumberScreen = 1,
  ScreenStateVpaEntry = 2,
  ScreenStateUpiIntentProcessing = 3,
  ScreenStateUpiCollectProcessing = 4,
};


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit3UPI")
@interface UPI : PaymentOption
@property (nonatomic, copy) NSString * _Nullable vpa;
@property (nonatomic, copy) NSString * _Nullable scheme;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit6Wallet")
@interface Wallet : PaymentOption
@property (nonatomic, copy) NSString * _Nullable maskedAccountNumber;
@property (nonatomic, copy) NSString * _Nullable phoneNumber;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#endif
#endif
